FROM ubuntu:22.04

ENV SBERT_MODEL=sentence-transformers/all-mpnet-base-v2
ENV OLLAMA_MODEL=phi3
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

RUN apt update -y && \
    apt upgrade -y && \
    apt install nginx -y && \
    apt install curl -y && \
    apt install dotnet-sdk-8.0 -y && \
    apt install supervisor -y && \
    apt install software-properties-common -y && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt update -y && \
    apt install python3.10 -y && \
    apt install python3.10-venv -y && \
    apt install pip -y && \
    ln -s /usr/bin/python3 /usr/bin/python

RUN pip3 install torch --index-url https://download.pytorch.org/whl/cu121 && \
    pip install transformers && \
    pip install sentence-transformers && \
    pip install Flask && \
    pip install waitress

RUN curl -fsSL https://ollama.com/install.sh | sh

RUN apt install -y postgresql-common git && \
    apt install -y postgresql-server-dev-14
RUN cd /tmp && \
    git clone https://github.com/pgvector/pgvector.git && \
    cd pgvector && \
    make && \
    make install
RUN apt install postgresql-14 -y

# set up options
RUN rm -rf /var/www/html/*
COPY ./wwwroot /var/www/html/
COPY ./etc /etc
COPY ./app/ /app/
WORKDIR /app
RUN echo "\\nexport PATH=\"\$PATH:/root/.dotnet/tools\"" >> ~/.bashrc
RUN echo "export TZ=UTC" >> ~/.bashrc

RUN /app/ollama/run-ollama.sh $OLLAMA_MODEL
RUN python -c "from sentence_transformers import SentenceTransformer; model = SentenceTransformer('$SBERT_MODEL')"
RUN dotnet tool install --global Rnwood.Smtp4dev    


EXPOSE 80

# CMD ["bash"] 
CMD ["/usr/bin/supervisord", "--configuration", "/etc/supervisor/supervisord.conf"]

# curl http://localhost:8080
# curl http://localhost:8085/generate-embedding?query=hello
# curl http://localhost:11434/api/generate -d '{ "model": "phi3", "prompt":"Why is the sky blue?" }'

# curl http://localhost:8080
# curl http://localhost:8080/sbert/generate-embedding?query=hello
# curl http://localhost:8080/ollama/api/generate -d '{ "model": "phi3", "prompt":"Why is the sky blue?" }'
# curl http://localhost:8080/mail
