version: '3'
services:

  summary-generation:
    build:
      dockerfile: DockerFile.summary-generation
      context: .
    ports: 
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  sentence-embedding:
    build:
      dockerfile: DockerFile.sentence-embedding
      context: .
    ports: 
      - "5080:5080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    
  fulltext-search:
    build:
      dockerfile: DockerFile.fulltext-search
      context: .
    ports: 
      - "9200:9200"
      - "9600:9600" 
      
  blob-storage:
    build:
      dockerfile: DockerFile.blob-storage
      context: .
    ports: 
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  vector-search:
    build:
      dockerfile: DockerFile.vector-search
      context: .
    ports: 
      - "6333:6333"
      - "6334:6334"
      
  # hybrid-api:
  #   build:
  #     dockerfile: DockerFile.hybrid-api
  #     context: .
  #   ports: 
  #     - "8080:8080"
            
  web-api:
    build:
      dockerfile: OobDev.Search.WebApi/Dockerfile
      context: .
    ports: 
      - "8080:8080"
      - "8081:8081"


